name: instagram_clone
description: 'Instagram Clone Mobile App'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  camerawesome: ^2.1.0
  dio: ^5.4.1
  flutter_native_splash: ^2.3.10
  flutter_secure_storage: ^10.0.0-beta.4
  freezed_annotation: ^2.4.1
  flutter_riverpod: ^2.4.10
  flutter_svg: ^2.0.9
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  go_router: ^15.0.0
  internet_connection_checker: ^1.0.0+1
  infinite_scroll_pagination: ^4.0.0
  image_cropper: ^9.1.0
  image_gallery_saver_plus: ^4.0.0
  image_picker: ^1.0.7
  json_annotation: ^4.8.1
  moment_dart: ^5.1.0
  photo_manager_image_provider: ^2.1.0
  riverpod_annotation: ^2.3.4
  riverpod_infinite_scroll: ^1.0.9
  stream_chat_flutter: ^9.7.0
  stream_chat_localizations: ^9.7.0
  video_player: ^2.8.2
  visibility_detector: ^0.4.0+2
  wechat_assets_picker: ^9.5.0
  file_picker: ^8.0.5
  archive: ^4.0.5
  carousel_slider: ^5.0.0

dependency_overrides:
  photo_manager: ^3.0.0-dev.2
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  custom_lint: ^0.7.3
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
